- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Import syncthing repo key
  apt_key:
    url: https://syncthing.net/release-key.txt

- name: Setup syncthing repo
  apt_repository:
    repo: "deb https://apt.syncthing.net/ syncthing stable"

- name: Install syncthing
  apt:
    name: syncthing