- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Install lsb-release
  apt:
    name: lsb-release

- name: Install curl
  apt:
    name: curl

- name: Install build-essential
  apt:
    name: build-essential

- name: Setup gpg key for nodejs repos
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Setup repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ primary_version }}.x {{ release }} main"
    update_cache: no

- name: Setup repos
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ primary_version }}.x {{ release }} main"
    update_cache: yes

- name: Install nodejs
  apt:
    name: nodejs