- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Install ca-certificates
  apt:
    name: ca-certificates

- name: Install curl
  apt:
    name: curl

- name: Install software-properties-common
  apt:
    name: software-properties-common

- name: Import docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present