- name: Setup PHP repo and install the latest on ubuntu based
  import_tasks: ubuntu_repo.yml
  when: (ansible_distribution == "Linux Mint") or (ansible_distribution == "Ubuntu")

- import_tasks: debian_install.yml
  when: ansible_os_family == "Debian"